ci(install): use corepack

diff --git a/.github/composite-actions/install/action.yml b/.github/composite-actions/install/action.yml
--- a/.github/composite-actions/install/action.yml
+++ b/.github/composite-actions/install/action.yml
@@ -15,13 +15,24 @@ runs:
       with:
         node-version-file: "package.json"
 
-    - name: Install specified npm version
+    - name: Setup corepack
       shell: bash
-      run: npm install --global "$(jq -r '.packageManager' package.json)"
+      run: |
+        corepack enable
+        corepack prepare --activate
+
+    - name: Validate input options
+      shell: bash
+      if: ${{ inputs.frozen-lockfile != 'false' && inputs.frozen-lockfile != 'true' }}
+      env:
+        FROZEN_LOCKFILE_OPTION: ${{ inputs.frozen-lockfile }}
+      run: |
+        echo "Invalid boolean value provided to frozen-lockfile option: $FROZEN_LOCKFILE_OPTION" >&2
+        exit 1
 
     - name: Install dependencies (frozen)
       shell: bash
-      if: ${{ inputs.frozen-lockfile != 'false' }}
+      if: ${{ inputs.frozen-lockfile == 'true' }}
       run: npm ci
 
     - name: Install dependencies (non-frozen)
